(function(global){
  'use strict';
  const E=global.XWNEngine;
  if(!E) throw new Error('XWNEngine must load before xwn4-runtime');
  const SYSTEMS=global.XWN_SYSTEMS||{};
  const A=global.XWN_ADAPTERS||{};
  const SWN_RULES=global.XWN_SWN_RULE_INDEX||[];
  const VERSION='4.0.0';
  const ACTIVE_SYSTEM_KEY='braseiro_xwn_active_system_v4';
  const SNAPSHOT_LIMIT=20;
  const old={makeInitialState:E.makeInitialState,importState:E.importState,exportState:E.exportState,queryRules:E.queryRules,queryRulesIndexed:E.queryRulesIndexed,performAction:E.performAction,playerAttack:E.playerAttack,travelTo:E.travelTo,exploreCurrentHex:E.exploreCurrentHex};

  function clone(v){return JSON.parse(JSON.stringify(v));}
  function clamp(v,min,max){const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(max,n)):min;}
  function cleanText(v,max=240){return String(v??'').replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,max);}
  function systemId(v){const id=String(v||'WWN').toUpperCase();return SYSTEMS[id]?id:'WWN';}
  function profile(v){return SYSTEMS[systemId(typeof v==='string'?v:v?.campaign?.system)]||SYSTEMS.WWN;}
  function activeSystem(){try{return systemId(global.localStorage?.getItem(ACTIVE_SYSTEM_KEY)||'WWN')}catch(_){return 'WWN'}}
  function setActiveSystem(id){id=systemId(id);try{global.localStorage?.setItem(ACTIVE_SYSTEM_KEY,id)}catch(_){}return id;}
  function hashString(str){let h=2166136261>>>0;for(let i=0;i<String(str).length;i++){h^=String(str).charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0;}
  function attrMod(score){return E.attrMod(clamp(score,3,18));}
  function axialDistanceKey(k){const m=String(k).match(/^(-?\d+),(-?\d+)$/);if(!m)return null;const q=+m[1],r=+m[2],s=-q-r;return Math.max(Math.abs(q),Math.abs(r),Math.abs(s));}
  function validHex(raw,k){const d=axialDistanceKey(k);if(d===null||d>120)return null;const m=k.match(/^(-?\d+),(-?\d+)$/),q=+m[1],r=+m[2];const h=(raw&&typeof raw==='object')?clone(raw):{};h.q=q;h.r=r;h.key=k;h.notes=Array.isArray(h.notes)?h.notes.slice(-100).map(n=>typeof n==='object'?clone(n):{text:cleanText(n)}):[];h.discovered=!!h.discovered;h.explored=!!h.explored;h.visited=!!h.visited;h.visitCount=clamp(h.visitCount||0,0,100000);return h;}

  function sanitizeCharacter(raw,sys='WWN'){
    const base=defaultPlayer(sys),src=(raw&&typeof raw==='object')?raw:{};const out={...base,...clone(src)};
    out.name=cleanText(out.name||base.name,80)||base.name;out.className=cleanText(out.className||base.className,80)||base.className;
    out.level=Math.round(clamp(out.level||1,1,20));out.maxHp=Math.round(clamp(out.maxHp||base.maxHp,1,999));out.hp=Math.round(clamp(out.hp??out.maxHp,0,out.maxHp));out.ac=Math.round(clamp(out.ac||base.ac,0,40));out.attackBonus=Math.round(clamp(out.attackBonus??base.attackBonus,-10,30));out.systemStrain=Math.round(clamp(out.systemStrain||0,0,30));
    const attrs={};for(const k of ['str','dex','con','int','wis','cha'])attrs[k]=Math.round(clamp(src.attrs?.[k]??base.attrs[k],3,18));out.attrs=attrs;out.mods=Object.fromEntries(Object.entries(attrs).map(([k,v])=>[k,attrMod(v)]));
    const skills={};for(const [k,v] of Object.entries({...base.skills,...(src.skills||{})})){const key=cleanText(k,32).toLowerCase().replace(/[^a-z0-9_áéíóúçãõ-]/gi,'');if(key)skills[key]=Math.round(clamp(v,-1,4));}out.skills=skills;
    out.inventory=(Array.isArray(src.inventory)?src.inventory:base.inventory).slice(0,100).map(x=>cleanText(x,120)).filter(Boolean);
    out.visualDescriptor=cleanText(src.visualDescriptor||base.visualDescriptor,500);
    const w={...base.weapon,...((src.weapon&&typeof src.weapon==='object')?src.weapon:{})};out.weapon={name:cleanText(w.name,80)||base.weapon.name,damage:/^\d+d\d+(?:\s*[+-]\s*\d+)?$/i.test(String(w.damage||''))?String(w.damage).replace(/\s+/g,''):base.weapon.damage,skill:cleanText(w.skill,30).toLowerCase()||base.weapon.skill,attr:['str','dex','con','int','wis','cha'].includes(w.attr)?w.attr:base.weapon.attr,shock:Math.round(clamp(w.shock||0,0,30)),shockAC:Math.round(clamp(w.shockAC||0,0,40)),normalRange:Math.round(clamp(w.normalRange||base.weapon.normalRange||10,1,2000)),maxRange:Math.round(clamp(w.maxRange||base.weapon.maxRange||30,1,5000)),kind:cleanText(w.kind||base.weapon.kind||'melee',20)};
    out.frail=!!src.frail;out.mortallyWounded=!!src.mortallyWounded;out.condition=cleanText(src.condition||base.condition,80)||'Apto';return out;
  }

  function defaultPlayer(sys){
    if(sys==='SWN')return {name:'Ira Venn',level:1,className:'Expert',hp:6,maxHp:6,ac:13,attackBonus:0,attrs:{str:10,dex:14,con:12,int:14,wis:12,cha:10},mods:{str:0,dex:1,con:0,int:1,wis:0,cha:0},skills:{notice:0,shoot:1,fix:0,pilot:0,program:0,connect:0,talk:0,exert:0,sneak:0,heal:0,lead:-1,punch:-1,stab:-1},weapon:{name:'Pistola laser',damage:'1d6',skill:'shoot',attr:'dex',shock:0,shockAC:0,normalRange:100,maxRange:300,kind:'ranged'},inventory:['Pistola laser','2 células tipo A','Roupa segura (AC 13)','Compad','Mochila'],systemStrain:0,condition:'Apto',frail:false,mortallyWounded:false,visualDescriptor:'exploradora espacial humana, roupa de viagem funcional, pistola laser e compad'};
    if(sys==='CWN')return {name:'Operador Zero',level:1,className:'Operator',hp:6,maxHp:6,ac:13,attackBonus:0,attrs:{str:10,dex:14,con:12,int:14,wis:12,cha:10},mods:{str:0,dex:1,con:0,int:1,wis:0,cha:0},skills:{notice:0,shoot:0,program:0,sneak:0,connect:0,talk:0},weapon:{name:'Arma não homologada',damage:'1d6',skill:'shoot',attr:'dex',shock:0,shockAC:0,normalRange:30,maxRange:100,kind:'ranged'},inventory:['Equipamento de rua'],systemStrain:0,condition:'Apto',frail:false,mortallyWounded:false,visualDescriptor:'operador cyberpunk urbano'};
    if(sys==='AWN')return {name:'Sobrevivente Zero',level:1,className:'Survivor',hp:6,maxHp:6,ac:12,attackBonus:0,attrs:{str:12,dex:12,con:14,int:10,wis:12,cha:10},mods:{str:0,dex:0,con:1,int:0,wis:0,cha:0},skills:{notice:0,survive:1,shoot:0,fix:0,exert:0},weapon:{name:'Arma não homologada',damage:'1d6',skill:'shoot',attr:'dex',shock:0,shockAC:0,normalRange:30,maxRange:100,kind:'ranged'},inventory:['Mochila de sobrevivência'],systemStrain:0,condition:'Apto',frail:false,mortallyWounded:false,visualDescriptor:'sobrevivente de ermo pós-apocalíptico'};
    const b=old.makeInitialState().player;return clone(b);
  }

  function domainNpcs(sys){
    if(sys==='SWN')return {ira:{id:'ira',name:'Ira Sen',role:'pilota independente',home:'0,0',location:'0,0',schedule:['0,0'],agenda:'conseguir combustível sem entregar a rota que descobriu',activity:'recalibrar um sensor portátil enquanto observa o cais orbital',alive:true,memory:[],knows:['Uma rota comercial ficou silenciosa há três dias.'],sourceSystem:'SWN'},sen:{id:'sen',name:'Sen Kade',role:'técnico de doca',home:'0,0',location:'0,0',schedule:['0,0'],agenda:'pagar uma dívida sem envolver a tripulação',activity:'trocar um painel chamuscado de um rebocador',alive:true,memory:[],knows:['O controle de tráfego está inspecionando cargueiros com rigor incomum.'],sourceSystem:'SWN'},vex:{id:'vex',name:'Vex Aru',role:'corretora de fretes',home:'0,0',location:'1,0',schedule:['1,0','0,0'],agenda:'descobrir quem está comprando mapas de navegação antigos',activity:'comparar contratos num tablet de vidro fosco',alive:true,memory:[],knows:['Alguém paga acima do mercado por dados pré-Silêncio.'],sourceSystem:'SWN'}};
    return {};
  }
  function domainFactions(sys){
    if(sys==='SWN')return [{id:'consorcio',name:'Consórcio de Navegação',force:1,cunning:2,wealth:3,location:'0,0',goal:'Controlar as rotas comerciais locais',progress:1,clock:6,known:true,sourceSystem:'SWN'},{id:'livres',name:'Capitães Livres',force:2,cunning:2,wealth:1,location:'1,0',goal:'Manter uma rota fora do controle do Consórcio',progress:0,clock:6,known:true,sourceSystem:'SWN'},{id:'arquivo',name:'Arquivo Mandato',force:1,cunning:3,wealth:2,location:'-1,0',goal:'Recuperar dados anteriores ao Silêncio',progress:0,clock:8,known:false,sourceSystem:'SWN'}];
    return [];
  }

  function applySystemState(state,sys){
    sys=systemId(sys);const p=profile(sys);state.version=VERSION;state.schema=Math.max(4,state.schema||1);state.campaign||={};state.campaign.system=sys;state.campaign.name=state.campaign.name&&state.campaign.system===sys?state.campaign.name:p.defaultCampaign;state.system={id:sys,label:p.label,barbaraSystemId:p.barbaraSystemId,corpusId:p.corpusId,corpusReady:!!p.corpusReady,mechanicsReady:!!p.mechanicsReady,rulesAuthority:p.rulesAuthority};state.rules={systemId:sys,corpusId:p.corpusId,ready:!!p.corpusReady,authority:p.rulesAuthority};state.diceCursor=Math.max(1,Number(state.diceCursor)||1);state.barbara||={version:'1.0.0',commit:'a31fdb9f9e361fc81b6a5f25c7646450311d0ce3',discovery:{},lastOccasion:'campaign_opening'};state.snapshotsMeta=Array.isArray(state.snapshotsMeta)?state.snapshotsMeta.slice(-SNAPSHOT_LIMIT):[];
    if(sys==='WWN'){state.atlas={...(state.atlas||{}),orientation:'flat',hexMiles:6};state.player=sanitizeCharacter(state.player,'WWN');return state;}
    state.atlas={id:`${sys.toLowerCase()}-domain`,orientation:p.mapOrientation,radius:Number(state.atlas?.radius)||4,source:'system-domain',fogPolicy:'enter-only-v2',kind:p.atlasKind,mapUnit:p.mapUnit};
    if(!state.hexes||!Object.keys(state.hexes).length||Object.values(state.hexes).some(h=>h.sourceSystem&&h.sourceSystem!==sys)||Object.values(state.hexes).some(h=>h.terrain))state.hexes=A.generateDomainHexes?A.generateDomainHexes(sys,state.atlas.radius):{};
    if(A.sanitizeHexes)state.hexes=A.sanitizeHexes(sys,state.hexes);state.player=sanitizeCharacter(state.player?.sourceSystem===sys?state.player:defaultPlayer(sys),sys);state.player.sourceSystem=sys;
    state.npcs=A.sanitizeEntityMap?A.sanitizeEntityMap(sys,state.npcs):{};if(!Object.keys(state.npcs||{}).length)state.npcs=domainNpcs(sys);state.factions=A.sanitizeFactionList?A.sanitizeFactionList(sys,state.factions):[];if(!state.factions.length)state.factions=domainFactions(sys);state.current=state.current&&state.hexes?.[`${state.current.q},${state.current.r}`]?state.current:{q:0,r:0};state.selected=state.selected&&state.hexes?.[`${state.selected.q},${state.selected.r}`]?state.selected:{q:0,r:0};state.campaign.weather=sys==='SWN'?(state.campaign.weather||'Tráfego orbital estável'):sys==='CWN'?(state.campaign.weather||'Chuva ácida leve'):(state.campaign.weather||'Vento seco');state.campaign.season=sys==='SWN'?'Ciclo orbital':sys==='CWN'?'Estação urbana':'Estação seca';state.world ||= {publicEvents:[],secretLedger:[],factionTraffic:[],siteMutations:[],rumorConfidence:{},clocks:[]};state.world.publicEvents ||= [];state.world.secretLedger ||= [];state.world.factionTraffic ||= [];state.world.siteMutations ||= [];state.world.rumorConfidence ||= {};state.world.clocks ||= [];
    return state;
  }

  function makeInitialState(sys=activeSystem()){
    sys=systemId(sys);let s=old.makeInitialState();if(sys!=='WWN'){s.campaign.name=profile(sys).defaultCampaign;s.hexes={};s.npcs={};s.factions=[];s.player=defaultPlayer(sys);s.journal=[];s.narrative=[];}
    s=applySystemState(s,sys);if(sys!=='WWN'){const h=s.hexes['0,0'];s.sceneTitle=h?.systemLabel||profile(sys).atlasLabel;s.narrative=[`Você chega a ${h?.systemLabel||'um ponto de fronteira'} sem um mapa confiável do que mudou por aqui. O lugar já estava em movimento antes da sua chegada.`,`Sinais de rotina, comércio e tensão aparecem primeiro no que as pessoas fazem e evitam fazer; o estado do setor não é entregue como relatório.`,`O que você sabe daqui em diante será aquilo que observar, ouvir, investigar ou viver em cena.`];}
    return s;
  }

  function importState(raw){
    const doc=typeof raw==='string'?JSON.parse(raw):clone(raw);if(!doc||typeof doc!=='object'||!doc.player||!doc.campaign||!doc.hexes)throw new Error('Save inválido.');const sys=systemId(doc.campaign.system||doc.system?.id||'WWN');const rawHexes=clone(doc.hexes||{});
    let base;
    if(sys==='WWN'){
      // O importador legado conhece o núcleo do save, mas as versões 3.4 e anteriores descartavam hexes fora do raio inicial.
      base=old.importState(doc);
      for(const [k,h0] of Object.entries(rawHexes)){const h=validHex(h0,k);if(!h)continue;if(base.hexes[k])base.hexes[k]={...base.hexes[k],...h};else{h.terrain=cleanText(h.terrain||'plains',30);h.tile=h.tile||`assets/hex_full/plains_lush.png`;h.road=!!h.road;h.poi=h.poi&&typeof h.poi==='object'?clone(h.poi):null;base.hexes[k]=h;}}
      const radius=Math.max(4,...Object.keys(base.hexes).map(k=>axialDistanceKey(k)||0));base.atlas.radius=radius;
    }else{
      base=makeInitialState(sys);for(const [k,h0] of Object.entries(rawHexes)){const h=validHex(h0,k);if(h)base.hexes[k]=h;}base={...base,...clone(doc),hexes:base.hexes};
    }
    base.player=sanitizeCharacter(doc.player,sys);base=applySystemState(base,sys);base.version=VERSION;return base;
  }
  function exportState(state){const s=clone(state);s.version=VERSION;s.schema=Math.max(4,s.schema||1);return JSON.stringify(s,null,2);}

  function characterDocument(state){return {schema:'braseiro-xwn-character-1',system:systemId(state?.campaign?.system),exportedAt:new Date().toISOString(),character:sanitizeCharacter(state?.player,systemId(state?.campaign?.system))};}
  function exportCharacter(state){return JSON.stringify(characterDocument(state),null,2);}
  function importCharacter(state,raw){const doc=typeof raw==='string'?JSON.parse(raw):clone(raw);if(!doc||doc.schema!=='braseiro-xwn-character-1'||!doc.character)throw new Error('Ficha JSON inválida.');const sys=systemId(state?.campaign?.system);if(systemId(doc.system)!==sys)throw new Error('Ficha pertence a outro sistema.');state.player=sanitizeCharacter(doc.character,sys);return state.player;}

  function snapshotState(state,label='Snapshot manual'){const clean=exportState(state);return {schema:'braseiro-xwn-snapshot-1',version:VERSION,label:cleanText(label,100),system:systemId(state?.campaign?.system),campaignId:cleanText(state?.campaign?.name,120),day:Number(state?.campaign?.day)||1,hour:Number(state?.campaign?.hour)||0,createdAt:new Date().toISOString(),sha:hashString(clean).toString(16),state:JSON.parse(clean)};}
  function restoreSnapshot(raw){const doc=typeof raw==='string'?JSON.parse(raw):clone(raw);if(!doc||doc.schema!=='braseiro-xwn-snapshot-1'||!doc.state)throw new Error('Snapshot inválido.');return importState(doc.state);}

  function nextDice(state){state.diceCursor=Math.max(1,Number(state.diceCursor)||1);const x=Math.sin((Number(state.seed)||1 + state.diceCursor*7919)*0.0174533)*10000;state.diceCursor+=1;return x-Math.floor(x);}
  function rollVirtual(state,sides=20,count=1){sides=Math.round(clamp(sides,2,100));count=Math.round(clamp(count,1,100));const rolls=[];for(let i=0;i<count;i++)rolls.push(1+Math.floor(nextDice(state)*sides));return {sides,count,rolls,total:rolls.reduce((a,b)=>a+b,0),diceCursor:state.diceCursor};}
  function skillCheck(state,skill,attr,difficulty=8,situational=0){const p=state.player,lvl=Number(p.skills?.[skill]??-1),mod=Number(p.mods?.[attr]??0),r=rollVirtual(state,6,2),pen=lvl<0?-1:0,total=r.total+Math.max(0,lvl)+mod+pen+clamp(situational,-2,2);return {roll:r.rolls,total,skill,skillLevel:lvl,attr,attrBonus:mod,penalty:pen,situational:clamp(situational,-2,2),difficulty,success:total>=difficulty};}

  function ruleIndexFor(state){const sys=systemId(state?.campaign?.system);return sys==='WWN'?(global.XWN_RULE_INDEX||[]):sys==='SWN'?SWN_RULES:[];}
  function rulesReady(state){const p=profile(state);return !!(p.corpusReady&&p.mechanicsReady&&ruleIndexFor(state).length);}
  function quickSWN(question){const q=String(question||'').toLowerCase();if(/dificuldade|per[ií]cia|skill|teste/.test(q))return 'SWN Revised: testes usam 2d6 + perícia + atributo contra dificuldade; sem nível-0, normalmente -1. Só se testa quando o resultado importa. [SWN Revised p. 47]';if(/iniciativa|initiative/.test(q))return 'SWN Revised: iniciativa individual usa 1d8 + modificador de Destreza, do maior para o menor, PCs vencem empates e a ordem não é rerrolada a cada rodada. Iniciativa por grupo é opcional. [SWN Revised p. 48]';if(/ataque|acertar|armor|\bac\b/.test(q))return 'SWN Revised: ataque usa 1d20 + bônus de ataque + perícia de combate + atributo relevante; igualar ou superar a AC acerta. Sem nível-0 na perícia da arma, -2. [SWN Revised p. 49]';if(/shock|choque|dano/.test(q))return 'SWN Revised: acerto causa dado de dano + atributo relevante; certas armas corpo a corpo aplicam Shock mesmo no erro contra AC adequada, e um acerto não causa menos que o Shock aplicável. [SWN Revised p. 49]';if(/cobertura|cover/.test(q))return 'SWN Revised: meia cobertura normalmente impõe -2 para acertar e cobertura quase total -4; posição de tiro preparada pode dar +2. [SWN Revised p. 49]';if(/defesa total|total defense/.test(q))return 'SWN Revised: Total Defense custa a Ação Principal, dá +2 AC até o próximo turno e imunidade a Shock corpo a corpo durante a rodada. [SWN Revised p. 50]';if(/retirada|withdrawal|recuo/.test(q))return 'SWN Revised: Fighting Withdrawal é uma Ação Principal que permite desengajar para depois se mover sem conceder ataque corpo a corpo gratuito. [SWN Revised p. 50]';if(/salvamento|saving|save/.test(q))return 'SWN Revised: salvamentos rolam 1d20 para igualar ou superar o alvo; 1 natural sempre falha e 20 natural sempre vence. [SWN Revised p. 46]';return 'Não há resposta rápida suficiente. O índice local SWN será consultado sem avançar a ficção.';}
  function queryRulesIndexed(state,question,index){const sys=systemId(state?.campaign?.system);if(!rulesReady(state)){const ans=`REGRA BLOQUEADA — ${profile(sys).label} ainda não possui corpus mecânico local homologado nesta build. Barbara/Rule Gate não permite usar regras de outro jogo como fallback.`;state.lastRuleAnswer=ans;return ans;}if(sys==='WWN')return old.queryRulesIndexed(state,question,index||global.XWN_RULE_INDEX);const hits=E.searchRuleIndex(question,SWN_RULES,4);const source=hits.map(h=>`SWN Revised p. ${h.page.bookPage} — ${h.page.section}: ${h.page.text}`).join('\n\n');const ans=`${quickSWN(question)}${source?`\n\nFONTES INDEXADAS LOCAIS\n${source}`:''}`;state.lastRuleAnswer=ans;return ans;}
  function queryRules(state,question){return queryRulesIndexed(state,question,ruleIndexFor(state));}

  function explicitMechanical(text){const q=String(text||'').toLowerCase();return /\b(teste|rolar|role|rolo|dado|dados|ataque|ataco|acertar|dano|salvamento|iniciativa|combat|attack|roll|check|save|damage)\b/.test(q);}
  function mechanicalBlocked(state,text){return explicitMechanical(text)&&!rulesReady(state);}

  function ensureTactical(state){if(state.combat?.system==='SWN')return state.combat;return null;}
  function actorDexMod(actor){const score=actor?.attrs?.dex??actor?.dex??10;return attrMod(score);}
  function allocPositions(count){const base=[[5,8],[5,2],[4,8],[6,2],[6,8],[4,2],[3,8],[7,2],[7,8],[3,2],[5,7],[5,3],[4,7],[6,3],[6,7],[4,3]];const out=[];for(let i=0;i<count;i++){if(i<base.length)out.push(base[i]);else out.push([i%11,Math.floor(i/11)%11]);}return out;}
  function startSWNTactical(state,enemies=[{id:'enemy-1',name:'Hostil',hp:6,ac:13,ab:1,attrs:{dex:10},weapon:{name:'Pistola',damage:'1d6',skill:'shoot',attr:'dex',normalRange:30,maxRange:100,kind:'ranged'}}],opts={}){
    if(systemId(state?.campaign?.system)!=='SWN')throw new Error('swn_tactical_wrong_system');if(!rulesReady(state))throw new Error('regra_sem_evidencia_canonica');const actors=[{id:'player',name:state.player.name,side:'pc',hp:state.player.hp,ac:state.player.ac,ab:state.player.attackBonus,attrs:clone(state.player.attrs),skills:clone(state.player.skills),weapon:clone(state.player.weapon),totalDefense:false,engaged:false},...enemies.map((x,i)=>({id:cleanText(x.id||`enemy-${i+1}`,40),name:cleanText(x.name||`Hostil ${i+1}`,60),side:'enemy',hp:Math.round(clamp(x.hp||5,1,999)),ac:Math.round(clamp(x.ac||10,5,30)),ab:Math.round(clamp(x.ab||0,-5,20)),attrs:clone(x.attrs||{dex:10}),skills:clone(x.skills||{shoot:0,stab:0,punch:0}),weapon:clone(x.weapon||{name:'Arma',damage:'1d6',skill:'shoot',attr:'dex',normalRange:30,maxRange:100,kind:'ranged'}),totalDefense:false,engaged:false}))];const pos=allocPositions(actors.length);actors.forEach((a,i)=>{a.x=pos[i][0];a.y=pos[i][1];a.initiative=rollVirtual(state,8,1).total+actorDexMod(a);});actors.sort((a,b)=>b.initiative-a.initiative||(a.side==='pc'?-1:1));state.combat={system:'SWN',round:1,turn:0,board:{width:11,height:11,obstacles:Array.isArray(opts.obstacles)?clone(opts.obstacles):[],difficult:Array.isArray(opts.difficult)?clone(opts.difficult):[],cover:Array.isArray(opts.cover)?clone(opts.cover):[]},actors,enemy:actors.find(a=>a.side==='enemy')||null,log:[]};return state.combat;}
  function distance(a,b){return Math.max(Math.abs(a.x-b.x),Math.abs(a.y-b.y));}
  function coverPenalty(combat,target){const c=(combat.board.cover||[]).find(x=>Number(x.x)===target.x&&Number(x.y)===target.y);return c?.grade==='full'?-4:c?-2:0;}
  function tacticalActor(combat,id){return combat?.actors?.find(a=>a.id===id);}
  function swAttack(state,attackerId='player',targetId){const c=ensureTactical(state);if(!c)throw new Error('swn_combat_not_active');const a=tacticalActor(c,attackerId),t=tacticalActor(c,targetId||c.actors.find(x=>x.side!==a?.side)?.id);if(!a||!t||a.hp<=0||t.hp<=0)throw new Error('invalid_combat_actor');const w=a.weapon||{},range=distance(a,t)*2,kind=w.kind||'ranged';let penalty=coverPenalty(c,t);if(kind==='melee'&&distance(a,t)>1)return {ok:false,reason:'fora_de_alcance_corpo_a_corpo'};if(kind!=='melee'){if(range>Number(w.maxRange||100))return {ok:false,reason:'fora_de_alcance'};if(range>Number(w.normalRange||30))penalty-=2;const adjacentEnemy=c.actors.some(x=>x.side!==a.side&&x.hp>0&&distance(a,x)<=1);if(adjacentEnemy){if(Number(w.normalRange||30)>50)return {ok:false,reason:'arma_duas_maos_em_melee'};penalty-=4;}}
    const d20=rollVirtual(state,20,1).total,skill=Number(a.skills?.[w.skill]??-1),skillPart=skill<0?-2:skill,mod=attrMod(a.attrs?.[w.attr]??10),total=d20+Number(a.ab||0)+skillPart+mod+penalty,hit=total>=Number(t.ac||10);let damage=0,shock=false;if(hit){const m=String(w.damage||'1d6').match(/(\d+)d(\d+)(?:([+-])(\d+))?/i);if(m){const rr=rollVirtual(state,+m[2],+m[1]);damage=rr.total+(m[3]?(m[3]==='+'?1:-1)*+m[4]:0)+mod;}damage=Math.max(damage,(Number(w.shock||0)>0&&Number(t.ac)<=Number(w.shockAC||0))?Number(w.shock||0)+mod:0);}else if(Number(w.shock||0)>0&&Number(t.ac)<=Number(w.shockAC||0)&&kind==='melee'&&!t.totalDefense){damage=Math.max(0,Number(w.shock)+mod);shock=damage>0;}t.hp=Math.max(0,t.hp-damage);if(t.id==='player')state.player.hp=t.hp;if(c.enemy?.id===t.id)c.enemy=t;c.log.push({round:c.round,type:'attack',attacker:a.id,target:t.id,d20,total,penalty,hit,shock,damage});return {ok:true,d20,total,penalty,hit,shock,damage,targetHp:t.hp,mechanics:`SWN p.49 — 1d20 + AB + perícia + atributo${penalty?` ${penalty}`:''} vs AC ${t.ac}.`};}
  function totalDefense(state,actorId='player'){const c=ensureTactical(state),a=tacticalActor(c,actorId);if(!a)throw new Error('invalid_combat_actor');if(a.totalDefense)return false;a.totalDefense=true;a.ac+=2;c.log.push({round:c.round,type:'total_defense',actor:a.id});return true;}
  function clearRoundDefense(c){for(const a of c.actors)if(a.totalDefense){a.totalDefense=false;a.ac-=2;}}
  function nextCombatTurn(state){const c=ensureTactical(state);if(!c)return null;c.turn++;if(c.turn>=c.actors.length){c.turn=0;c.round++;clearRoundDefense(c);}return c.actors[c.turn];}

  function performAction(state,text){const sys=systemId(state?.campaign?.system);if(mechanicalBlocked(state,text))return {ok:false,narrative:[`O Mestre não resolve essa ação mecanicamente porque ${profile(sys).label} não tem um corpus RULE homologado nesta build.`],mechanics:'RULE GATE — regra canônica ausente; nenhum turno mecânico foi inventado.'};if(sys==='WWN')return old.performAction(state,text);const q=String(text||'').toLowerCase();if(sys==='SWN'&&/\b(ataco|ataque|attack|disparo|shoot)\b/.test(q)&&ensureTactical(state)){const r=swAttack(state,'player');return {ok:r.ok,narrative:[r.ok?(r.hit?'Seu ataque encontra uma abertura real na defesa do alvo.':r.shock?'O golpe não entra limpo, mas a pressão do corpo a corpo ainda cobra seu preço.':'O alvo se mantém fora da linha decisiva do ataque.'):'A ação não pode ser executada nessa posição.'],mechanics:r.mechanics||r.reason};}
    // Ações narrativas continuam possíveis mesmo em perfis fail-closed; apenas a mecânica específica é bloqueada.
    state.continuity ||= {actionLedger:[]};state.continuity.actionLedger ||= [];state.continuity.actionLedger.push({type:'player_action',system:sys,day:state.campaign.day,hour:state.campaign.hour,text:cleanText(text,500)});state.narrative=[`Você age dentro de ${profile(sys).label}; o mundo responde apenas com fatos já estabelecidos e sinais perceptíveis.`,`Nenhuma regra específica é inventada só para fazer a cena andar.`];return {ok:true,narrative:state.narrative,mechanics:'SEM TESTE — ação ficcional sem incerteza mecânica explícita.'};}

  function travelTo(state,q,r){const sys=systemId(state?.campaign?.system);if(sys==='WWN')return old.travelTo(state,q,r);const from=`${state.current.q},${state.current.r}`,to=`${q},${r}`,h=state.hexes?.[to];if(!h)return {ok:false,narrative:['O destino não existe no atlas atual.'],mechanics:''};const a={q:state.current.q,r:state.current.r},b={q:+q,r:+r};if(E.axialDistance(a,b)!==1)return {ok:false,narrative:['Selecione uma zona adjacente para deslocamento local.'],mechanics:''};state.current={q:+q,r:+r};state.selected={q:+q,r:+r};h.discovered=true;h.visited=true;h.visitCount=(h.visitCount||0)+1;state.campaign.hour=(Number(state.campaign.hour)||0)+1;state.narrative=[`A transição até ${h.systemLabel||h.domainTerrain||to} não entrega um relatório do lugar: os primeiros sinais aparecem conforme você entra na zona.`,`O que mudou aqui será descoberto pela cena, não presumido pelo mapa.`];return {ok:true,narrative:state.narrative,mechanics:'DESLOCAMENTO DE DOMÍNIO — sem teste mecânico de navegação inventado.'};}
  function exploreCurrentHex(state){const sys=systemId(state?.campaign?.system);if(sys==='WWN')return old.exploreCurrentHex(state);const h=state.hexes?.[`${state.current.q},${state.current.r}`];if(!h)return {ok:false,narrative:['Zona ausente.'],mechanics:''};h.explored=true;state.campaign.hour=(Number(state.campaign.hour)||0)+2;state.narrative=[`Você dedica tempo a ler a zona de perto. Atividade, marcas de passagem, infraestrutura e pessoas presentes ganham forma aos poucos.`,`O que não foi observado continua desconhecido; exploração não transforma ausência de evidência em certeza.`];return {ok:true,narrative:state.narrative,mechanics:'EXPLORAÇÃO DE DOMÍNIO — nenhuma regra específica ausente foi simulada.'};}

  function sourceStatus(){return {WWN:{ready:true,source:'Worlds Without Number SRD 1.0'},SWN:{ready:true,source:'Stars Without Number Revised Edition'},CWN:{ready:false,source:null},AWN:{ready:false,source:null}};}
  function auditState(state){const sys=systemId(state?.campaign?.system),errors=[];if(state.version!==VERSION)errors.push('version');if(state.system?.id!==sys)errors.push('system.id');if(state.rules?.systemId!==sys)errors.push('rules.systemId');if(sys!=='WWN'&&A.validateState){const r=A.validateState(state);if(!r.ok)errors.push(...r.errors);}if(!state.player||!state.hexes||!state.campaign||!state.continuity||!state.world)errors.push('missing_core_state');return {ok:!errors.length,system:sys,rulesReady:rulesReady(state),errors};}

  Object.assign(E,{VERSION,STORAGE_KEY:'braseiro_xwn_v400',ACTIVE_SYSTEM_KEY,systemId,profile,activeSystem,setActiveSystem,makeInitialState,importState,exportState,sanitizeCharacter,exportCharacter,importCharacter,snapshotState,restoreSnapshot,rollVirtual,skillCheck,ruleIndexFor,rulesReady,sourceStatus,queryRules,queryRulesIndexed,explicitMechanical,startSWNTactical,swAttack,totalDefense,nextCombatTurn,performAction,travelTo,exploreCurrentHex,auditState});
  global.XWN4Runtime=E;
  if(typeof module!=='undefined'&&module.exports)module.exports=E;
})(typeof window!=='undefined'?window:globalThis);
