(function(global){
  'use strict';
  const E=global.XWNEngine,SYSTEMS=global.XWN_SYSTEMS||{},SNAPS=global.XWNSnapshotStore,AUDIO=global.XWNLocalAudio;
  if(!E?.systemId)return;
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const DICE_KEY='braseiro_xwn_virtual_dice_v4';
  function state(){try{const raw=localStorage.getItem(E.STORAGE_KEY);return raw?E.importState(raw):E.makeInitialState(E.activeSystem());}catch(e){console.warn('xwn4 state',e);return E.makeInitialState(E.activeSystem());}}
  function save(s){localStorage.setItem(E.STORAGE_KEY,E.exportState(s));return s;}
  function download(name,text,type='application/json'){const a=document.createElement('a'),u=URL.createObjectURL(new Blob([text],{type}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),600);}
  function filePicker(accept,handler){const i=document.createElement('input');i.type='file';i.accept=accept;i.hidden=true;i.onchange=async()=>{const f=i.files?.[0];if(f)await handler(f);i.remove();};document.body.appendChild(i);i.click();}
  function injectStyle(){const st=document.createElement('style');st.textContent=`
    [hidden]{display:none!important}.xwn4-tools{margin-top:14px;padding-top:12px;border-top:1px solid var(--line)}.xwn4-row{display:flex;gap:7px;flex-wrap:wrap;align-items:center}.xwn4-row select,.xwn4-row input[type=text]{border:1px solid var(--line);border-radius:9px;background:var(--surface);color:var(--ink);padding:8px}.xwn4-status{margin-top:7px;font:11px/1.45 system-ui;color:var(--muted)}.xwn4-dice{display:flex;gap:5px;flex-wrap:wrap;margin:7px 0}.xwn4-dice button{border:1px solid var(--line);border-radius:9px;padding:6px 9px;background:var(--surface2);font:700 11px system-ui}.xwn4-dice-result{min-height:20px;font:800 13px/1.4 ui-monospace,monospace}.xwn4-snapshot-list,.xwn4-audio-list{display:grid;gap:6px;margin-top:8px}.xwn4-snapshot,.xwn4-audio-item{display:flex;align-items:center;justify-content:space-between;gap:7px;padding:7px;border:1px solid var(--line);border-radius:9px;background:var(--soft)}.xwn4-snapshot small,.xwn4-audio-item small{display:block;color:var(--muted)}.xwn4-tactical{margin-top:9px;border:1px solid var(--line);border-radius:10px;padding:8px;background:color-mix(in srgb,var(--surface2) 82%,#000 18%)}.xwn4-board{display:grid;grid-template-columns:repeat(11,18px);grid-template-rows:repeat(11,18px);gap:1px;width:max-content;max-width:100%;overflow:auto;margin-top:6px}.xwn4-cell{width:18px;height:18px;border:1px solid #ffffff13;background:#0002;position:relative}.xwn4-cell.cover{background:#46708a66}.xwn4-cell.obstacle{background:#231f1b}.xwn4-actor{position:absolute;inset:1px;border-radius:50%;display:grid;place-items:center;font:800 7px/1 system-ui;background:#e9f2f7;color:#101820;border:1px solid #fff;z-index:2}.xwn4-actor.enemy{background:#a24743;color:#fff}.xwn4-combat-order{display:flex;gap:4px;flex-wrap:wrap;margin-top:5px}.xwn4-combat-order span{font:700 9px system-ui;border:1px solid var(--line);border-radius:999px;padding:3px 5px}.xwn4-rule-warning{color:#a43c34;font-weight:800}.xwn4-barbara-pill{display:inline-block;border:1px solid var(--line);border-radius:999px;padding:4px 7px;font:800 9px/1 system-ui;margin-left:6px}.xwn4-system-badge{font:800 10px/1 system-ui;padding:5px 7px;border:1px solid var(--line);border-radius:999px;background:var(--soft)}
    body[data-xwn-system="SWN"] .hex{width:114px!important;height:132px!important;clip-path:polygon(50% 0,100% 25%,100% 75%,50% 100%,0 75%,0 25%)!important}
  `;document.head.appendChild(st);}
  function installSystemSelector(){const settings=$('page-settings')?.querySelector('.panel');if(!settings)return;const box=document.createElement('div');box.className='xwn4-tools';box.innerHTML=`<div class="eyebrow">SISTEMA XWN • ISOLAMENTO DE DOMÍNIO</div><div class="xwn4-row"><label>Sistema <select id="xwnSystemSelect">${Object.values(SYSTEMS).map(s=>`<option value="${esc(s.id)}">${esc(s.label)}</option>`).join('')}</select></label><span id="xwnSystemBadge" class="xwn4-system-badge"></span></div><div id="xwnSystemStatus" class="xwn4-status"></div>`;settings.prepend(box);const sel=$('xwnSystemSelect');sel.value=E.activeSystem();sel.onchange=()=>{const next=E.systemId(sel.value),cur=E.activeSystem();if(next===cur)return;if(!confirm(`Trocar de ${SYSTEMS[cur]?.label||cur} para ${SYSTEMS[next]?.label||next}? Cada sistema mantém save, regras e atlas próprios.`)){sel.value=cur;return;}E.setActiveSystem(next);location.reload();};updateSystemStatus();}
  function updateSystemStatus(){const s=state(),p=E.profile(s),ready=E.rulesReady(s),badge=$('xwnSystemBadge'),status=$('xwnSystemStatus');document.body.dataset.xwnSystem=E.systemId(s.campaign.system);if(badge)badge.textContent=`${p.short} • ${ready?'REGRAS OK':'FAIL-CLOSED'}`;if(status)status.innerHTML=ready?`Corpus mecânico ativo: <b>${esc(p.rulesAuthority||p.corpusId)}</b>. Motor Barbara: 1.0.0.`:`<span class="xwn4-rule-warning">Mecânica bloqueada:</span> ${esc(p.label)} ainda não possui corpus RULE local homologado. Ficção, save, mapa, áudio e mundo continuam disponíveis sem inventar regras.`;const rs=$('ruleIndexStatus');if(rs){const n=E.ruleIndexFor(s).length;rs.textContent=ready?`Índice offline: ${n} entradas/páginas mecânicas de ${p.label}. Rule Gate ativo.`:`${p.label}: consulta mecânica fail-closed até corpus homologado.`;}}
  function installCharacterTools(){const panel=$('page-character')?.querySelector('.panel');if(!panel)return;const box=document.createElement('div');box.className='xwn4-tools';box.innerHTML=`<div class="eyebrow">FICHA PORTÁTIL • JSON</div><div class="xwn4-row"><button class="secondary" id="xwnCharExport">Exportar ficha JSON</button><button class="secondary" id="xwnCharImport">Importar ficha JSON</button></div><div id="xwnCharStatus" class="xwn4-status">A ficha é validada e não pode cruzar de um sistema XWN para outro.</div>`;panel.appendChild(box);$('xwnCharExport').onclick=()=>{const s=state();download(`ficha_${E.systemId(s.campaign.system).toLowerCase()}_${Date.now()}.json`,E.exportCharacter(s));};$('xwnCharImport').onclick=()=>filePicker('application/json,.json',async f=>{try{const s=state();E.importCharacter(s,await f.text());save(s);$('xwnCharStatus').textContent='Ficha importada e sanitizada. Recarregando…';setTimeout(()=>location.reload(),250);}catch(e){$('xwnCharStatus').textContent=`Falha: ${e.message}`;}});}
  async function refreshSnapshots(){const list=$('xwnSnapshotList');if(!list||!SNAPS?.supported())return;const sys=E.activeSystem(),rows=await SNAPS.list(sys);list.innerHTML=rows.length?rows.map(r=>`<div class="xwn4-snapshot" data-id="${esc(r.id)}"><div><b>${esc(r.label)}</b><small>${esc(r.campaignId)} • dia ${r.day} ${String(r.hour).padStart(2,'0')}:00 • ${new Date(r.createdAt).toLocaleString('pt-BR')}</small></div><div class="xwn4-row"><button class="secondary" data-act="restore">Restaurar</button><button class="ghost" data-act="delete">Excluir</button></div></div>`).join(''):'<span class="muted-note">Nenhum snapshot local.</span>';list.querySelectorAll('[data-id]').forEach(row=>{row.querySelector('[data-act=restore]').onclick=async()=>{if(!confirm('Restaurar este snapshot? O estado atual será substituído.'))return;const snap=await SNAPS.get(row.dataset.id),s=E.restoreSnapshot(snap);save(s);location.reload();};row.querySelector('[data-act=delete]').onclick=async()=>{await SNAPS.remove(row.dataset.id);refreshSnapshots();};});}
  function installSnapshotTools(){const panel=$('page-settings')?.querySelector('.panel');if(!panel)return;const box=document.createElement('div');box.className='xwn4-tools';box.innerHTML=`<div class="eyebrow">SNAPSHOTS • SEGURANÇA DA CAMPANHA</div><div class="xwn4-row"><button class="secondary" id="xwnSnapshotSave">Salvar snapshot local</button><button class="secondary" id="xwnSnapshotDownload">Baixar snapshot</button><button class="secondary" id="xwnSnapshotImport">Restaurar arquivo</button></div><div id="xwnSnapshotStatus" class="xwn4-status"></div><div id="xwnSnapshotList" class="xwn4-snapshot-list"></div>`;panel.appendChild(box);$('xwnSnapshotSave').onclick=async()=>{try{const s=state(),snap=E.snapshotState(s,`Dia ${s.campaign.day} • ${String(s.campaign.hour).padStart(2,'0')}:00`);if(!SNAPS?.supported())throw new Error('IndexedDB indisponível');await SNAPS.put(snap);$('xwnSnapshotStatus').textContent='Snapshot salvo no aparelho.';refreshSnapshots();}catch(e){$('xwnSnapshotStatus').textContent=`Snapshot local indisponível: ${e.message}`;}};$('xwnSnapshotDownload').onclick=()=>{const snap=E.snapshotState(state(),'Snapshot exportado');download(`snapshot_xwn_${Date.now()}.json`,JSON.stringify(snap,null,2));};$('xwnSnapshotImport').onclick=()=>filePicker('application/json,.json',async f=>{try{const s=E.restoreSnapshot(await f.text());if(!confirm(`Restaurar snapshot de ${s.campaign.name}?`))return;save(s);location.reload();}catch(e){$('xwnSnapshotStatus').textContent=`Falha: ${e.message}`;}});void refreshSnapshots();}
  function diceCursor(){try{return Math.max(1,Number(localStorage.getItem(`${DICE_KEY}_${E.activeSystem()}`))||1)}catch(_){return 1}}
  function setDiceCursor(v){try{localStorage.setItem(`${DICE_KEY}_${E.activeSystem()}`,String(v))}catch(_){}}
  function rollDie(sides){const s=state(),tmp={seed:s.seed||12345,diceCursor:diceCursor()},r=E.rollVirtual(tmp,sides,1);setDiceCursor(tmp.diceCursor);return r.rolls[0];}
  function installDice(){const scene=$('page-play')?.querySelector('.scene-card');if(!scene)return;const box=document.createElement('div');box.className='xwn4-tools';box.innerHTML=`<div class="eyebrow">DADOS VIRTUAIS</div><div class="xwn4-dice">${[4,6,8,10,12,20,100].map(d=>`<button data-die="${d}">d${d}</button>`).join('')}</div><div class="xwn4-dice-result" id="xwnDiceResult">—</div>`;const composer=scene.querySelector('.input-label');scene.insertBefore(box,composer);box.querySelectorAll('[data-die]').forEach(b=>b.onclick=()=>{const d=Number(b.dataset.die),r=rollDie(d);$('xwnDiceResult').textContent=`d${d} → ${r}`;});}
  async function refreshAudio(){const list=$('xwnLocalAudioList');if(!list)return;if(!AUDIO?.supported()){list.innerHTML='<span class="muted-note">Biblioteca local indisponível neste navegador.</span>';return;}const rows=await AUDIO.list();list.innerHTML=rows.length?rows.map(r=>`<div class="xwn4-audio-item" data-id="${esc(r.id)}"><div><b>${esc(r.name)}</b><small>${Math.round(r.size/1024)} KB • local</small></div><div class="xwn4-row"><button class="secondary" data-act="play">▶</button><button class="ghost" data-act="delete">Excluir</button></div></div>`).join(''):'<span class="muted-note">Nenhuma música/ambiência local importada.</span>';list.querySelectorAll('[data-id]').forEach(row=>{row.querySelector('[data-act=play]').onclick=()=>AUDIO.play(row.dataset.id,{loop:true,volume:.5}).catch(e=>$('xwnLocalAudioStatus').textContent=e.message);row.querySelector('[data-act=delete]').onclick=async()=>{await AUDIO.remove(row.dataset.id);refreshAudio();};});}
  function installAudioLibrary(){const panel=$('page-audio')?.querySelector('.panel');if(!panel)return;const box=document.createElement('div');box.className='xwn4-tools';box.innerHTML=`<div class="eyebrow">MÚSICA / AMBIÊNCIA LOCAL</div><div class="xwn4-row"><button class="secondary" id="xwnAudioImport">Importar áudio</button><button class="ghost" id="xwnAudioStop">Parar faixa local</button></div><div id="xwnLocalAudioStatus" class="xwn4-status">Arquivos ficam apenas no aparelho via IndexedDB.</div><div id="xwnLocalAudioList" class="xwn4-audio-list"></div>`;panel.appendChild(box);$('xwnAudioImport').onclick=()=>filePicker('audio/*',async f=>{try{await AUDIO.add(f,f.name);$('xwnLocalAudioStatus').textContent=`Importado: ${f.name}`;refreshAudio();}catch(e){$('xwnLocalAudioStatus').textContent=`Falha: ${e.message}`;}});$('xwnAudioStop').onclick=()=>AUDIO?.stop();void refreshAudio();}
  function layoutPointy(){if(E.activeSystem()!=='SWN')return;const map=$('hexMap');if(!map)return;for(const b of map.querySelectorAll('.hex')){const q=Number(b.dataset.q),r=Number(b.dataset.r),x=114*(q+r/2),y=99*r;b.style.left=`${410+x-57}px`;b.style.top=`${360+y-66}px`;b.style.width='114px';b.style.height='132px';b.style.clipPath='polygon(50% 0,100% 25%,100% 75%,50% 100%,0 75%,0 25%)';}}
  function installMapObserver(){const map=$('hexMap');if(!map)return;const ob=new MutationObserver(()=>queueMicrotask(layoutPointy));ob.observe(map,{childList:true});layoutPointy();}
  function renderTacticalBoard(){let s;try{s=state()}catch(_){return}const host=$('xwnTacticalHost');if(!host)return;const c=s.combat;if(E.activeSystem()!=='SWN'||!c||c.system!=='SWN'){host.hidden=true;return;}host.hidden=false;const cells=[];for(let y=0;y<11;y++)for(let x=0;x<11;x++){const obstacle=(c.board.obstacles||[]).some(o=>+o.x===x&&+o.y===y),cover=(c.board.cover||[]).some(o=>+o.x===x&&+o.y===y),actor=(c.actors||[]).find(a=>a.hp>0&&a.x===x&&a.y===y);cells.push(`<div class="xwn4-cell${obstacle?' obstacle':''}${cover?' cover':''}">${actor?`<span class="xwn4-actor ${actor.side==='enemy'?'enemy':''}" title="${esc(actor.name)} • PV ${actor.hp} • AC ${actor.ac}">${esc(actor.name).slice(0,2).toUpperCase()}</span>`:''}</div>`);}host.innerHTML=`<div class="eyebrow">COMBATE TÁTICO SWN • 11×11 • 2 m/célula</div><div class="xwn4-combat-order">${(c.actors||[]).map((a,i)=>`<span>${i===c.turn?'▶ ':''}${esc(a.name)} ${a.initiative} • PV ${a.hp}</span>`).join('')}</div><div class="xwn4-board">${cells.join('')}</div>`;}
  function installTactical(){const box=$('combatBox');if(!box)return;const host=document.createElement('div');host.id='xwnTacticalHost';host.className='xwn4-tactical';host.hidden=true;box.insertAdjacentElement('afterend',host);const ob=new MutationObserver(()=>setTimeout(renderTacticalBoard,0));ob.observe(box,{attributes:true,childList:true,subtree:true});setInterval(()=>{if(!document.hidden)renderTacticalBoard();},1200);renderTacticalBoard();if(E.activeSystem()==='SWN'&&$('fleeBtn'))$('fleeBtn').textContent='Retirada';}
  function markBarbara(){const h=$('page-play')?.querySelector('.scene-card .card-head .eyebrow');if(h&&!h.querySelector('.xwn4-barbara-pill'))h.insertAdjacentHTML('beforeend',' <span class="xwn4-barbara-pill">BARBARA 1.0</span>');}
  function init(){injectStyle();installSystemSelector();installCharacterTools();installSnapshotTools();installDice();installAudioLibrary();installMapObserver();installTactical();markBarbara();updateSystemStatus();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else setTimeout(init,0);
})(typeof window!=='undefined'?window:globalThis);
