import { chromium } from 'playwright';
const base=process.env.XWN_URL||'http://127.0.0.1:8765/index.html';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1280,height:900}});const errors=[];
page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
const nav=id=>page.locator(`.bottom-nav button[data-page="${id}"]`);
async function setSystem(id){await page.evaluate(id=>localStorage.setItem('braseiro_xwn_active_system_v4',id),id);await page.reload({waitUntil:'networkidle'});await page.waitForTimeout(250);}
await page.goto(base,{waitUntil:'networkidle'});await page.waitForTimeout(300);
if(!(await page.title()).includes('XWN 4.0'))throw new Error('wrong title');
if(await page.locator('#storyFeed p').count()<4)throw new Error('campaign opening is not a story scene');
if(!(await page.locator('#xwnSystemSelect').count()))throw new Error('system selector missing');
if(!(await page.locator('#xwnCharExport').count()))throw new Error('character JSON tools missing');
if(!(await page.locator('#xwnSnapshotSave').count()))throw new Error('snapshot tools missing');
if(!(await page.locator('[data-die="20"]').count()))throw new Error('virtual dice missing');
await page.locator('[data-die="20"]').click();if(!(await page.locator('#xwnDiceResult').textContent()).includes('d20'))throw new Error('virtual die did not roll');
await setSystem('SWN');
if((await page.locator('body').getAttribute('data-xwn-system'))!=='SWN')throw new Error('SWN host not active');
if(!(await page.locator('#xwnSystemStatus').textContent()).includes('Stars Without Number'))throw new Error('SWN status missing');
if(await page.locator('#hexMap .hex').count()<20)throw new Error('SWN sector map absent');
const clip=await page.locator('#hexMap .hex').first().evaluate(e=>getComputedStyle(e).clipPath);if(!clip.includes('50% 0'))throw new Error('SWN pointy-top rendering missing');
const beforeDay=await page.locator('#dayLabel').textContent(),beforeTime=await page.locator('#timeLabel').textContent();
await nav('rules').click();await page.locator('#rulesInput').fill('Como funciona iniciativa?');await page.locator('#sendRule').click();await page.waitForTimeout(150);const ans=await page.locator('#rulesAnswer').textContent();if(!/1d8/i.test(ans))throw new Error('SWN rule query not using SWN rules');if(await page.locator('#dayLabel').textContent()!==beforeDay||await page.locator('#timeLabel').textContent()!==beforeTime)throw new Error('rule query advanced fiction');
await nav('character').click();if(!(await page.locator('#xwnCharImport').isVisible()))throw new Error('character import hidden');
await nav('audio').click();if(!(await page.locator('#xwnAudioImport').isVisible()))throw new Error('local audio import missing');
await setSystem('CWN');
if(!(await page.locator('#xwnSystemStatus').textContent()).includes('ainda não possui corpus RULE'))throw new Error('CWN fail-closed status missing');
await nav('play').click();await page.locator('#actionInput').fill('Faço um teste de ataque');await page.locator('#sendAction').click();await page.waitForTimeout(150);const mechanics=await page.locator('#mechanicsText').textContent();if(!/RULE GATE/i.test(mechanics))throw new Error('CWN mechanical action did not fail closed');
await setSystem('WWN');if(await page.locator('#storyFeed p').count()<4)throw new Error('WWN story opening regressed');
if(errors.length)throw new Error('browser errors: '+errors.join(' | '));
console.log('XWN4 browser smoke OK');await browser.close();
