const assert=require('assert');
global.window=global; require('../rules-index.js'); require('../hex-library.js');
const E=require('../engine.js');
let count=0; const ok=(x,msg)=>{assert.ok(x,msg);count++;};
let s=E.makeInitialState();
ok(E.VERSION==='1.5.0','version');
ok(Object.keys(s.hexes).length===37,'37 hexes');
ok(s.atlas.orientation==='flat','flat orientation');
ok(new Set(Object.values(s.hexes).map(h=>h.tile)).size>=20,'map tile diversity');
ok(global.XWN_HEX_LIBRARY.length===30,'30 hex library variants');
ok(global.XWN_HEX_LIBRARY.every(x=>x.width===224&&x.height===194),'flat tile dimensions');
ok(E.npcsAt(s,'0,0').map(n=>n.id).includes('mara'),'mara present');
ok(E.activeVisualEntities(s).some(e=>e.id==='player'),'player in token strip');
E.setEntityToken(s,'mara',{dataUrl:'data:image/jpeg;base64,YWJj',fileName:'mara.jpg',mimeType:'image/jpeg'});
let bundle=E.makeGeminiImageBundle(s);
ok(bundle.references.some(r=>r.entityId==='mara'),'gemini bundle embeds mara token');
ok(/Não troque rosto|identidade visual/i.test(bundle.prompt),'gemini continuity instruction');
let serialized=E.exportState(s); let restored=E.importState(serialized);
ok(restored.visual.tokens.mara.fileName==='mara.jpg','token persists save/load');
let stateProbe=JSON.stringify({day:s.campaign.day,hour:s.campaign.hour,current:s.current,journal:s.journal.length,narrative:s.narrative,world:s.world});
let rule=E.queryRulesIndexed(s,'Como estabilizar um ferido mortal?',global.XWN_RULE_INDEX);
ok(rule.includes('WWN SRD p. 48'),'indexed source page 48');
ok(rule.includes('FONTES INDEXADAS LOCAIS'),'indexed sources header');
ok(stateProbe===JSON.stringify({day:s.campaign.day,hour:s.campaign.hour,current:s.current,journal:s.journal.length,narrative:s.narrative,world:s.world}),'rule channel preserves state');
let beforeDel=s.npcs.del.location; E.exploreCurrentHex(s); let afterDel=s.npcs.del.location;
ok(beforeDel!==afterDel,'npc schedule moves offscreen');
for(let i=0;i<8;i++){ if(s.combat)s.combat=null; E.exploreCurrentHex(s); }
ok((s.world.siteMutations||[]).length>0,'site mutations occur');
ok((s.campaign.worldTurn||0)>0,'faction turn occurs');
ok((s.world.secretLedger||[]).some(e=>e.type==='npc_move'),'secret npc movement ledger');
let q=E.queryRulesIndexed(s,'Como funciona explorar um hex?',global.XWN_RULE_INDEX);
ok(q.includes('WWN SRD p. 54'),'hex exploration page source');
let d=E.queryRulesIndexed(s,'Como funciona iniciativa?',global.XWN_RULE_INDEX);
ok(d.includes('WWN SRD p. 45'),'initiative page source');
let legacy=E.makeInitialState(); delete legacy.visual; delete legacy.world; delete legacy.npcs.selka; Object.values(legacy.hexes).forEach(h=>delete h.tile); let mig=E.importState(JSON.stringify(legacy));
ok(!!mig.npcs.selka,'legacy migration adds new canonical NPC');
ok(Object.values(mig.hexes).every(h=>!!h.tile),'legacy migration assigns tile variants');
ok(Array.isArray(mig.world.clocks)&&mig.world.clocks.length>0,'legacy migration adds world clocks');
console.log(`PASS ${count} assertions`);
